#!/bin/bash -e

# Enable a default set of software repositories
# Run this script as root.

# Install public key for the Debian fasttrack repo.
# https://fasttrack.debian.net/
apt-get -qq update
apt-get -yy install fasttrack-archive-keyring

# Overwrite sources list:
printf "# Official repos:
deb https://deb.debian.org/debian/ bullseye main non-free contrib
deb https://security.debian.org/ bullseye-security main contrib non-free
deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free

# Fasttrack repo:
deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib
deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib

# Source repo for Sid, used to compile packages from source:
deb-src https://deb.debian.org/debian/ sid main contrib non-free" > /etc/apt/sources.list

apt-get -qq update
