#!/bin/bash -e

# Enable a default set of software repositories
# Run this script as root.

printf "deb https://deb.debian.org/debian/ bullseye main non-free contrib
deb https://security.debian.org/ bullseye-security main contrib non-free
deb https://deb.debian.org/debian/ bullseye-updates main contrib non-free
deb https://deb.debian.org/debian/ bullseye-backports main contrib non-free
deb-src https://deb.debian.org/debian/ sid main contrib non-free" > /etc/apt/sources.list

apt-get update
apt-get -y install fasttrack-archive-keyring
apt-add-repository -y "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib"
apt-add-repository -y -u "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib"
