#!/bin/bash -e

# Enables a selection of core apps on a standard Debian installation.
# Run this script as root.

apt-get -qq update
apt-get -yy install \
  audacity \
  blender \
  brasero \
  clamtk \
  ffmpeg \
  flatpak \
  filezilla \
  freecad \
  gchempaint \
  gcu-bin \
  ghostwriter \
  gimp \
  gnome-software-plugin-flatpak \
  gnome-subtitle \
  homebank \
  ibus-libpinyin \
  imagej \
  inkscape \
  keepassxc \
  lame \
  lyx \
  mkvtoolnix-gui \
  musescore3 \
  nextcloud-desktop \
  pdfarranger \
  pitivi \
  puddletag \
  r-base \
  remmina \
  rhythmbox-plugin-alternative-toolbar \
  simplescreenrecorder \
  soundconverter \
  virtualbox \
  virtualbox-guest-additions-iso

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak -y install flathub \
  com.microsoft.Teams \
  com.prusa3d.PrusaSlicer \
  org.freedesktop.Platform.ffmpeg-full/21.08 \
  org.jitsi.jitsi-meet \  
  org.mozilla.firefox \
  org.zotero.Zotero \
  us.zoom.Zoom
