#!/bin/bash -e

# Enable Debian Fasttrack repository:
# https://fasttrack.debian.net/
# Run this script as root.

apt-get update
apt-get -y install fasttrack-archive-keyring
apt-add-repository -y "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-fasttrack main contrib"
apt-add-repository -y "deb https://fasttrack.debian.net/debian-fasttrack/ bullseye-backports-staging main contrib"
apt-get update
