#!/bin/bash -e
# Install Oracle VirtualBox on Debian-based systems
# Run this script as root

apt-add-repository -y "deb https://download.virtualbox.org/virtualbox/debian bullseye contrib"
sudo apt-get update
sudo apt-get -y install virtualbox-6.1
